name: budgi
description: Budgi Flutter project.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  intl: any
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: any

flutter:
  generate: true
  uses-material-design: true
