name: budgi
description: Budgi Flutter project.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  jiffy: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: any

flutter:
  uses-material-design: true
