include: package:flutter_lints/flutter.yaml

# https://dart.dev/guides/language/analysis-options
analyzer:
  exclude:
    - lib/l10n/**
# https://dart.dev/lints
linter:
  rules:
    - prefer_relative_imports
    - prefer_single_quotes
