FROM nginx:alpine

COPY ./build/web/assets/ /usr/share/nginx/html
COPY ./build/web/canvaskit/ /usr/share/nginx/html
COPY ./build/web/icons/ /usr/share/nginx/html
COPY ./build/web/splash/ /usr/share/nginx/html
COPY ./build/web/*.* /usr/share/nginx/html
