name: budgi
description: Budgi Flutter project.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.3.1
  flutter_native_splash: ^2.3.10
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_fonts: ^6.2.0
  intl: any
  meta: any
  month_year_picker: ^0.3.0+1
  package_info_plus: ^5.0.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: any
  mockito: any
  test: any

flutter:
  assets:
    - fonts/Open_Sans/
  generate: true
  uses-material-design: true

flutter_native_splash:
  color: "#acb7b9"
  image: "icon/logo-400.png"
  color_dark: "#34495e"
  image_dark: "icon/logo-400.png"
