version: '3'

services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=budgi
      - POSTGRES_PASSWORD=budgi
      - POSTGRES_DB=budgi
    ports:
      - '5432:5432'
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
