services:

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=budgi
      - POSTGRES_PASSWORD=budgi
      - POSTGRES_DB=budgi
    ports:
      - '5432:5432'
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    environment:
      - REDIS_PASSWORD=budgi
      - REDIS_PORT=6379
    command: redis-server --requirepass budgi
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
