version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=budgi
      - POSTGRES_PASSWORD=budgi
      - POSTGRES_DB=budgi
    ports:
      - '5432:5432'
    volumes:
      - ./data/pgsql-app:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 5s

  budgi:
    image: ghcr.io/h4j4x/budgi:latest
    environment:
      - TOKEN_SECRET=7r5z4PsjmT8RvtjKUy2z9wlZjoAJ/zEW3lAB8KWuAiLDg2o5uQo6l0x2/pEXaPeKPbpO4gp+h+7lL2iGw9+lzQ==
      - DATASOURCE_URL=jdbc:postgresql://postgres/budgi
      - DATASOURCE_USERNAME=budgi
      - DATASOURCE_PASSWORD=budgi
      - DATASOURCE_DRIVER=org.postgresql.Driver
      - DATASOURCE_DDL=update
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
