services:

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=budgi
      - POSTGRES_PASSWORD=budgi
      - POSTGRES_DB=budgi
    volumes:
      - ./data/pgsql-app:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 5s

  redis:
    image: redis:alpine
    environment:
      - REDIS_PASSWORD=budgi
      - REDIS_PORT=6379
    command: redis-server --requirepass budgi
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis-app:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 5s

  budgi:
    image: ghcr.io/h4j4x/budgi:latest
    restart: unless-stopped
    environment:
      - TOKEN_SECRET=7r5z4PsjmT8RvtjKUy2z9wlZjoAJ/zEW3lAB8KWuAiLDg2o5uQo6l0x2/pEXaPeKPbpO4gp+h+7lL2iGw9+lzQ==
      - DATASOURCE_URL=jdbc:postgresql://postgres/budgi
      - DATASOURCE_USERNAME=budgi
      - DATASOURCE_PASSWORD=budgi
      - DATASOURCE_DRIVER=org.postgresql.Driver
      - DATASOURCE_SCHEMA=budgi
      - DATABASE_CLEAN_ON_START=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=budgi
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: "wget -q localhost:8080/manage/health -O- | grep -o UP | wc -l | grep 5 || exit 1"
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 5s

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      budgi:
        condition: service_healthy
