token:
  secret: ${TOKEN_SECRET}
  expirationInDays: ${TOKEN_EXPIRATION_IN_DAYS:7}
management:
  endpoint:
    health:
      showDetails: always
  endpoints:
    web:
      basePath: /manage
      exposure:
        include: health
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driverClassName: ${DATASOURCE_DRIVER}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jackson:
    defaultPropertyInclusion: non_null
    deserialization:
      failOnUnknownProperties: false
    serialization:
      failOnEmptyBeans: false
      writeDatesAsTimestamps: false
  jpa:
    hibernate:
      ddlAuto: validate
    open-in-view: false
  liquibase:
    changeLog: classpath:data/changelog-master.yml
    databaseChangeLogLockTable: changelog_lock
    databaseChangeLogTable: changelogs
springdoc:
  apiDocs:
    path: /api/v1/docs
  packagesToScan: com.sp1ke.budgi.api.web
  swaggerUi:
    disableSwaggerDefaultUrl: true
    path: /api/v1/docs-ui
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.springframework.web: INFO
