token:
  secret: ${TOKEN_SECRET}
  expirationInDays: ${TOKEN_EXPIRATION_IN_DAYS:7}
management:
  endpoint:
    health:
      showDetails: always
  endpoints:
    web:
      basePath: /manage
      exposure:
        include: health
spring:
  cache:
    type: redis
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      database: 0
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      repositories:
        enabled: false
  datasource:
    driverClassName: ${DATASOURCE_DRIVER}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jackson:
    defaultPropertyInclusion: non_null
    deserialization:
      adjustDatesToContextTimeZone: false
      failOnUnknownProperties: false
    serialization:
      failOnEmptyBeans: false
      writeDatesAsTimestamps: false
  jpa:
    hibernate:
      ddlAuto: validate
    openInView: false
    properties:
      hibernate:
        defaultSchema: ${DATASOURCE_SCHEMA:public}
        formatSql: true
    showSql: false
  liquibase:
    changeLog: classpath:data/changelog-master.yml
    databaseChangeLogLockTable: changelog_lock
    databaseChangeLogTable: changelogs
    defaultSchema: ${DATASOURCE_SCHEMA:public}
    dropFirst: ${DATABASE_CLEAN_ON_START:false}
springdoc:
  apiDocs:
    path: /api/v1/docs
  packagesToScan: com.sp1ke.budgi.api.web
  swaggerUi:
    disableSwaggerDefaultUrl: true
    path: /api/v1/docs-ui
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.sql: INFO
    org.springframework.web: INFO
