name: Flutter Publish

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
      - run: flutter --version
        working-directory: ./flutter
      - run: flutter pub get
        working-directory: ./flutter
      - name: Build web
        run: flutter build web --release --dart-define="DATA_PROVIDER=spring" --dart-define="SPRING_URL=http://budgi:8080/api/v1"
        working-directory: ./flutter
      - id: getversion
        run: echo "app_version=$(cat VERSION)" >> "$GITHUB_ENV"
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./flutter
          push: true
          tags: ghcr.io/h4j4x/budgi-app:latest,ghcr.io/h4j4x/budgi-app:$app_version
