name: Flutter Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
      - run: flutter --version
        working-directory: ./flutter
      - run: flutter pub get
        working-directory: ./flutter
      - run: flutter test
        working-directory: ./flutter
